# Generated by Django 4.2.2 on 2023-06-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_alter_comments_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                    to='core.users', verbose_name='Автор'),
        ),
    ]
